---
- hosts: all
  user: vagrant
  become_user: root
  vars:
    phantom_js_file: phantomjs-1.9.8-linux-x86_64
    phantom_js_ext: .tar.bz2
    phantom_js_md5: 4ea7aa79e45fbc487a63ef4788a18ef7
    phantom_js_sha256: a1d9628118e270f26c4ddd1d7f3502a93b48ede334b8585d11c1c3ae7bc7163a

  tasks:
    - name : Update APT package cache
      apt: update_cache=yes
      become: yes

    - name: Install python-apt  (Required by ANSIBLE)
      command: apt-get -y install python-apt
      become: yes

    - name : Update all packages to the latest version
      apt: upgrade=dist
      become: yes

    - name: Remove Apache2
      apt: name={{ item }} state=absent purge=yes force=yes
      with_items:
        - apache2
        - apache2-utils
      become: yes

    - name: Install packages
      apt: name={{ item }} state=installed update_cache=yes cache_valid_time=3600
      with_items:
        - git-core
        - postfix
        - mailutils
        - vim
        - nginx
        - curl
        - nodejs
        - npm
        - build-essential
        - redis-server
        - libqt4-dev
        - libqtwebkit-dev
        - imagemagick
        - qt4-dev-tools
        - libqt4-dev
        - libqt4-core
        - libqt4-gui
        - python-dev
        - python-virtualenv
        - libmysqlclient-dev
        - nodejs-legacy
      become: yes

    # Install PhantomJS
    - stat: path=/usr/local/bin/{{ phantom_js_file }}/bin/phantomjs
      register: phantomjs_exists

    - include: setup_phantom_js.yml
      when: phantomjs_exists|failed

    # Install specified node requirements.
    - name: Add Nodesource apt key
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
        id: "68576280"
        state: present
      become: yes

    - name: Add NodeSource repositories for NodeJS
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - "deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main"
        - "deb-src https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main"
      register: node_repo
      become: yes

    - name: Install NodeJS
      apt: "name=nodejs=4* state=present"
      become: yes

    - stat: path=/usr/bin/node
      register: node_bin

    - name: Link the nodejs binary to the node command
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        state: link
      when: node_bin.stat.exists == False
      become: yes

    # Install specified node requirements.
    - name: Install global node packages
      npm: name={{ item }} global=yes
      with_items:
        - grunt-cli
        - bower
      become: yes

    - file: path=~/provision/node state=directory
      become: no

    - copy: src=./node/dependencies.sh dest=~/provision/node/dependencies.sh mode=775
      become: no

    - name: Installing Node dependencies
      shell: /usr/bin/env bash ~/provision/node/dependencies.sh
      become: no
